import type { Metadata } from "next";
import Link from "next/link";
import StampIcon from "@/icons/StampIcon";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="flex flex-col min-h-screen">
				<header className="px-4 lg:px-6 h-14 flex justify-start">
					<Link href="/" className="flex items-center gap-2">
						<StampIcon className="h-6 w-6" />
						<span className="text-lg font-semibold">Vacation Postcards</span>
					</Link>
				</header>
				<main className="flex-grow">{children}</main>
				<footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
					<p className="text-xs text-muted-foreground">
						&copy; 2024 Vacation Postcards. All rights reserved.
					</p>
					<nav className="sm:ml-auto flex gap-4 sm:gap-6">
						<Link
							href="#"
							className="text-xs hover:underline underline-offset-4"
							prefetch={false}
						>
							Terms of Service
						</Link>
						<Link
							href="#"
							className="text-xs hover:underline underline-offset-4"
							prefetch={false}
						>
							Privacy
						</Link>
					</nav>
				</footer>
			</body>
		</html>
	);
}
